// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	types.proto
	snapshot.proto

It has these top-level messages:
	RobustId
	RobustMessage
	RaftLog
	Timestamp
	Snapshot
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RobustMessage_RobustType int32

const (
	RobustMessage_CREATE_SESSION   RobustMessage_RobustType = 0
	RobustMessage_DELETE_SESSION   RobustMessage_RobustType = 1
	RobustMessage_IRC_FROM_CLIENT  RobustMessage_RobustType = 2
	RobustMessage_IRC_TO_CLIENT    RobustMessage_RobustType = 3
	RobustMessage_PING             RobustMessage_RobustType = 4
	RobustMessage_MESSAGE_OF_DEATH RobustMessage_RobustType = 5
	RobustMessage_CONFIG           RobustMessage_RobustType = 6
	RobustMessage_STATE            RobustMessage_RobustType = 7
	RobustMessage_ANY              RobustMessage_RobustType = 8
)

var RobustMessage_RobustType_name = map[int32]string{
	0: "CREATE_SESSION",
	1: "DELETE_SESSION",
	2: "IRC_FROM_CLIENT",
	3: "IRC_TO_CLIENT",
	4: "PING",
	5: "MESSAGE_OF_DEATH",
	6: "CONFIG",
	7: "STATE",
	8: "ANY",
}
var RobustMessage_RobustType_value = map[string]int32{
	"CREATE_SESSION":   0,
	"DELETE_SESSION":   1,
	"IRC_FROM_CLIENT":  2,
	"IRC_TO_CLIENT":    3,
	"PING":             4,
	"MESSAGE_OF_DEATH": 5,
	"CONFIG":           6,
	"STATE":            7,
	"ANY":              8,
}

func (x RobustMessage_RobustType) String() string {
	return proto1.EnumName(RobustMessage_RobustType_name, int32(x))
}
func (RobustMessage_RobustType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type RaftLog_LogType int32

const (
	RaftLog_COMMAND    RaftLog_LogType = 0
	RaftLog_NOOP       RaftLog_LogType = 1
	RaftLog_ADDPEER    RaftLog_LogType = 2
	RaftLog_REMOVEPEER RaftLog_LogType = 3
	RaftLog_BARRIER    RaftLog_LogType = 4
)

var RaftLog_LogType_name = map[int32]string{
	0: "COMMAND",
	1: "NOOP",
	2: "ADDPEER",
	3: "REMOVEPEER",
	4: "BARRIER",
}
var RaftLog_LogType_value = map[string]int32{
	"COMMAND":    0,
	"NOOP":       1,
	"ADDPEER":    2,
	"REMOVEPEER": 3,
	"BARRIER":    4,
}

func (x RaftLog_LogType) String() string {
	return proto1.EnumName(RaftLog_LogType_name, int32(x))
}
func (RaftLog_LogType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type RobustId struct {
	Id    uint64 `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
	Reply uint64 `protobuf:"fixed64,2,opt,name=reply" json:"reply,omitempty"`
}

func (m *RobustId) Reset()                    { *m = RobustId{} }
func (m *RobustId) String() string            { return proto1.CompactTextString(m) }
func (*RobustId) ProtoMessage()               {}
func (*RobustId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RobustId) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RobustId) GetReply() uint64 {
	if m != nil {
		return m.Reply
	}
	return 0
}

type RobustMessage struct {
	Id      *RobustId                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Session *RobustId                `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
	Type    RobustMessage_RobustType `protobuf:"varint,3,opt,name=type,enum=proto.RobustMessage_RobustType" json:"type,omitempty"`
	Data    string                   `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	// TODO: use oneof for the following to save space?
	UnixNano        int64    `protobuf:"varint,5,opt,name=unix_nano,json=unixNano" json:"unix_nano,omitempty"`
	Servers         []string `protobuf:"bytes,6,rep,name=servers" json:"servers,omitempty"`
	CurrentMaster   string   `protobuf:"bytes,7,opt,name=current_master,json=currentMaster" json:"current_master,omitempty"`
	ClientMessageId uint64   `protobuf:"varint,8,opt,name=client_message_id,json=clientMessageId" json:"client_message_id,omitempty"`
	Revision        uint64   `protobuf:"varint,9,opt,name=revision" json:"revision,omitempty"`
	RemoteAddr      string   `protobuf:"bytes,10,opt,name=remote_addr,json=remoteAddr" json:"remote_addr,omitempty"`
}

func (m *RobustMessage) Reset()                    { *m = RobustMessage{} }
func (m *RobustMessage) String() string            { return proto1.CompactTextString(m) }
func (*RobustMessage) ProtoMessage()               {}
func (*RobustMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RobustMessage) GetId() *RobustId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RobustMessage) GetSession() *RobustId {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *RobustMessage) GetType() RobustMessage_RobustType {
	if m != nil {
		return m.Type
	}
	return RobustMessage_CREATE_SESSION
}

func (m *RobustMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *RobustMessage) GetUnixNano() int64 {
	if m != nil {
		return m.UnixNano
	}
	return 0
}

func (m *RobustMessage) GetServers() []string {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *RobustMessage) GetCurrentMaster() string {
	if m != nil {
		return m.CurrentMaster
	}
	return ""
}

func (m *RobustMessage) GetClientMessageId() uint64 {
	if m != nil {
		return m.ClientMessageId
	}
	return 0
}

func (m *RobustMessage) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *RobustMessage) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

type RaftLog struct {
	Index uint64          `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Term  uint64          `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	Type  RaftLog_LogType `protobuf:"varint,3,opt,name=type,enum=proto.RaftLog_LogType" json:"type,omitempty"`
	Data  []byte          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *RaftLog) Reset()                    { *m = RaftLog{} }
func (m *RaftLog) String() string            { return proto1.CompactTextString(m) }
func (*RaftLog) ProtoMessage()               {}
func (*RaftLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RaftLog) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RaftLog) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RaftLog) GetType() RaftLog_LogType {
	if m != nil {
		return m.Type
	}
	return RaftLog_COMMAND
}

func (m *RaftLog) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto1.RegisterType((*RobustId)(nil), "proto.RobustId")
	proto1.RegisterType((*RobustMessage)(nil), "proto.RobustMessage")
	proto1.RegisterType((*RaftLog)(nil), "proto.RaftLog")
	proto1.RegisterEnum("proto.RobustMessage_RobustType", RobustMessage_RobustType_name, RobustMessage_RobustType_value)
	proto1.RegisterEnum("proto.RaftLog_LogType", RaftLog_LogType_name, RaftLog_LogType_value)
}

func init() { proto1.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x8a, 0xda, 0x40,
	0x14, 0xdd, 0x98, 0x68, 0xe2, 0xb5, 0xea, 0xec, 0xed, 0x52, 0x42, 0xfb, 0x60, 0x10, 0x0a, 0xe9,
	0x3e, 0x48, 0xd9, 0xfd, 0x82, 0x54, 0x47, 0x9b, 0x62, 0x12, 0x99, 0x84, 0x42, 0x9f, 0x42, 0x76,
	0x67, 0x2a, 0x81, 0x35, 0x91, 0x49, 0x5c, 0xd6, 0x5f, 0xe8, 0x37, 0xf4, 0x5f, 0xfa, 0x6b, 0x25,
	0x13, 0xdd, 0x76, 0xa1, 0x7d, 0x9a, 0x39, 0xe7, 0x9e, 0x39, 0xf7, 0x5e, 0xce, 0xc0, 0xa0, 0x3e,
	0xee, 0x45, 0x35, 0xdb, 0xcb, 0xb2, 0x2e, 0xb1, 0xab, 0x8e, 0xe9, 0x47, 0xb0, 0x58, 0x79, 0x77,
	0xa8, 0x6a, 0x9f, 0xe3, 0x08, 0x3a, 0x39, 0xb7, 0x35, 0x47, 0x73, 0x7b, 0xac, 0x93, 0x73, 0xbc,
	0x82, 0xae, 0x14, 0xfb, 0x87, 0xa3, 0xdd, 0x51, 0x54, 0x0b, 0xa6, 0x3f, 0x0c, 0x18, 0xb6, 0x4f,
	0x02, 0x51, 0x55, 0xd9, 0x56, 0xe0, 0xe4, 0xf9, 0xdd, 0xe0, 0x66, 0xdc, 0xda, 0xcf, 0xce, 0xa6,
	0xca, 0xe8, 0x03, 0x98, 0x95, 0xa8, 0xaa, 0xbc, 0x2c, 0x94, 0xd5, 0x3f, 0x54, 0xe7, 0x3a, 0xde,
	0x82, 0xd1, 0x4c, 0x69, 0xeb, 0x8e, 0xe6, 0x8e, 0x6e, 0x26, 0x2f, 0x74, 0xa7, 0x7e, 0x27, 0x94,
	0x1c, 0xf7, 0x82, 0x29, 0x31, 0x22, 0x18, 0x3c, 0xab, 0x33, 0xdb, 0x70, 0x34, 0xb7, 0xcf, 0xd4,
	0x1d, 0xdf, 0x41, 0xff, 0x50, 0xe4, 0x4f, 0x69, 0x91, 0x15, 0xa5, 0xdd, 0x75, 0x34, 0x57, 0x67,
	0x56, 0x43, 0x84, 0x59, 0x51, 0xa2, 0xdd, 0x0c, 0x24, 0x1f, 0x85, 0xac, 0xec, 0x9e, 0xa3, 0xbb,
	0x7d, 0x76, 0x86, 0xf8, 0x1e, 0x46, 0xf7, 0x07, 0x29, 0x45, 0x51, 0xa7, 0xbb, 0xac, 0xaa, 0x85,
	0xb4, 0x4d, 0x65, 0x3a, 0x3c, 0xb1, 0x81, 0x22, 0xf1, 0x1a, 0x2e, 0xef, 0x1f, 0x72, 0xa5, 0x6a,
	0x87, 0x4a, 0x73, 0x6e, 0x5b, 0x8e, 0xe6, 0x1a, 0x6c, 0xdc, 0x16, 0x4e, 0xc3, 0xfa, 0x1c, 0xdf,
	0x82, 0x25, 0xc5, 0x63, 0xae, 0xd6, 0xef, 0x2b, 0xc9, 0x33, 0xc6, 0x09, 0x0c, 0xa4, 0xd8, 0x95,
	0xb5, 0x48, 0x33, 0xce, 0xa5, 0x0d, 0xaa, 0x17, 0xb4, 0x94, 0xc7, 0xb9, 0x9c, 0xfe, 0xd4, 0x00,
	0xfe, 0xec, 0x8b, 0x08, 0xa3, 0x39, 0xa3, 0x5e, 0x42, 0xd3, 0x98, 0xc6, 0xb1, 0x1f, 0x85, 0xe4,
	0xa2, 0xe1, 0x16, 0x74, 0x4d, 0xff, 0xe2, 0x34, 0x7c, 0x0d, 0x63, 0x9f, 0xcd, 0xd3, 0x25, 0x8b,
	0x82, 0x74, 0xbe, 0xf6, 0x69, 0x98, 0x90, 0x0e, 0x5e, 0xc2, 0xb0, 0x21, 0x93, 0xe8, 0x4c, 0xe9,
	0x68, 0x81, 0xb1, 0xf1, 0xc3, 0x15, 0x31, 0xf0, 0x0a, 0x48, 0x40, 0xe3, 0xd8, 0x5b, 0xd1, 0x34,
	0x5a, 0xa6, 0x0b, 0xea, 0x25, 0x9f, 0x49, 0x17, 0x01, 0x7a, 0xf3, 0x28, 0x5c, 0xfa, 0x2b, 0xd2,
	0xc3, 0x3e, 0x74, 0xe3, 0xc4, 0x4b, 0x28, 0x31, 0xd1, 0x04, 0xdd, 0x0b, 0xbf, 0x11, 0x6b, 0xfa,
	0x4b, 0x03, 0x93, 0x65, 0xdf, 0xeb, 0x75, 0xb9, 0x6d, 0xbe, 0x4b, 0x5e, 0x70, 0xf1, 0xa4, 0x7e,
	0x82, 0xc1, 0x5a, 0xd0, 0x64, 0x53, 0x0b, 0xb9, 0x53, 0xc1, 0x1b, 0x4c, 0xdd, 0xf1, 0xfa, 0x45,
	0xc8, 0x6f, 0xce, 0x21, 0xb7, 0x3e, 0xb3, 0x75, 0xb9, 0xfd, 0x4f, 0xb6, 0xaf, 0xda, 0x6c, 0xa7,
	0x5f, 0xc0, 0x3c, 0x89, 0x70, 0x00, 0xe6, 0x3c, 0x0a, 0x02, 0x2f, 0x5c, 0x90, 0x8b, 0x66, 0x9b,
	0x30, 0x8a, 0x36, 0x44, 0x6b, 0x68, 0x6f, 0xb1, 0xd8, 0x50, 0xca, 0x48, 0x07, 0x47, 0x00, 0x8c,
	0x06, 0xd1, 0x57, 0xaa, 0xb0, 0xde, 0x14, 0x3f, 0x79, 0x8c, 0xf9, 0x94, 0x11, 0xe3, 0xae, 0xa7,
	0x9a, 0xdf, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x38, 0xea, 0x84, 0xe4, 0x1d, 0x03, 0x00, 0x00,
}
