// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	types.proto
	snapshot.proto

It has these top-level messages:
	RobustId
	RobustMessage
	SnapshotLog
	Timestamp
	Snapshot
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RobustMessage_RobustType int32

const (
	RobustMessage_CREATE_SESSION   RobustMessage_RobustType = 0
	RobustMessage_DELETE_SESSION   RobustMessage_RobustType = 1
	RobustMessage_IRC_FROM_CLIENT  RobustMessage_RobustType = 2
	RobustMessage_IRC_TO_CLIENT    RobustMessage_RobustType = 3
	RobustMessage_PING             RobustMessage_RobustType = 4
	RobustMessage_MESSAGE_OF_DEATH RobustMessage_RobustType = 5
	RobustMessage_CONFIG           RobustMessage_RobustType = 6
	RobustMessage_ANY              RobustMessage_RobustType = 7
)

var RobustMessage_RobustType_name = map[int32]string{
	0: "CREATE_SESSION",
	1: "DELETE_SESSION",
	2: "IRC_FROM_CLIENT",
	3: "IRC_TO_CLIENT",
	4: "PING",
	5: "MESSAGE_OF_DEATH",
	6: "CONFIG",
	7: "ANY",
}
var RobustMessage_RobustType_value = map[string]int32{
	"CREATE_SESSION":   0,
	"DELETE_SESSION":   1,
	"IRC_FROM_CLIENT":  2,
	"IRC_TO_CLIENT":    3,
	"PING":             4,
	"MESSAGE_OF_DEATH": 5,
	"CONFIG":           6,
	"ANY":              7,
}

func (x RobustMessage_RobustType) String() string {
	return proto1.EnumName(RobustMessage_RobustType_name, int32(x))
}
func (RobustMessage_RobustType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type RobustId struct {
	Id    int64 `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
	Reply int64 `protobuf:"fixed64,2,opt,name=reply" json:"reply,omitempty"`
}

func (m *RobustId) Reset()                    { *m = RobustId{} }
func (m *RobustId) String() string            { return proto1.CompactTextString(m) }
func (*RobustId) ProtoMessage()               {}
func (*RobustId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RobustId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RobustId) GetReply() int64 {
	if m != nil {
		return m.Reply
	}
	return 0
}

type RobustMessage struct {
	Id      *RobustId                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Session *RobustId                `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
	Type    RobustMessage_RobustType `protobuf:"varint,3,opt,name=type,enum=proto.RobustMessage_RobustType" json:"type,omitempty"`
	Data    string                   `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	// TODO: use oneof for the following to save space?
	Servers         []string `protobuf:"bytes,5,rep,name=servers" json:"servers,omitempty"`
	CurrentMaster   string   `protobuf:"bytes,6,opt,name=current_master,json=currentMaster" json:"current_master,omitempty"`
	ClientMessageId uint64   `protobuf:"varint,7,opt,name=client_message_id,json=clientMessageId" json:"client_message_id,omitempty"`
	Revision        uint64   `protobuf:"varint,8,opt,name=revision" json:"revision,omitempty"`
}

func (m *RobustMessage) Reset()                    { *m = RobustMessage{} }
func (m *RobustMessage) String() string            { return proto1.CompactTextString(m) }
func (*RobustMessage) ProtoMessage()               {}
func (*RobustMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RobustMessage) GetId() *RobustId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RobustMessage) GetSession() *RobustId {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *RobustMessage) GetType() RobustMessage_RobustType {
	if m != nil {
		return m.Type
	}
	return RobustMessage_CREATE_SESSION
}

func (m *RobustMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *RobustMessage) GetServers() []string {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *RobustMessage) GetCurrentMaster() string {
	if m != nil {
		return m.CurrentMaster
	}
	return ""
}

func (m *RobustMessage) GetClientMessageId() uint64 {
	if m != nil {
		return m.ClientMessageId
	}
	return 0
}

func (m *RobustMessage) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

type SnapshotLog struct {
	Index uint64         `protobuf:"fixed64,1,opt,name=index" json:"index,omitempty"`
	Term  uint64         `protobuf:"fixed64,2,opt,name=term" json:"term,omitempty"`
	Msg   *RobustMessage `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *SnapshotLog) Reset()                    { *m = SnapshotLog{} }
func (m *SnapshotLog) String() string            { return proto1.CompactTextString(m) }
func (*SnapshotLog) ProtoMessage()               {}
func (*SnapshotLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SnapshotLog) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SnapshotLog) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *SnapshotLog) GetMsg() *RobustMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto1.RegisterType((*RobustId)(nil), "proto.RobustId")
	proto1.RegisterType((*RobustMessage)(nil), "proto.RobustMessage")
	proto1.RegisterType((*SnapshotLog)(nil), "proto.SnapshotLog")
	proto1.RegisterEnum("proto.RobustMessage_RobustType", RobustMessage_RobustType_name, RobustMessage_RobustType_value)
}

func init() { proto1.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xad, 0xb1, 0x31, 0x64, 0x10, 0xe0, 0x4c, 0x39, 0x58, 0xbd, 0xc4, 0x42, 0x6a, 0xe5, 0xf6,
	0x10, 0x55, 0xe4, 0x0b, 0x10, 0x59, 0xa8, 0x25, 0xb0, 0xab, 0xb5, 0x2f, 0x3d, 0xad, 0x9c, 0x78,
	0x45, 0x2d, 0x05, 0x6c, 0xed, 0x6e, 0xa2, 0xf2, 0x19, 0xfd, 0xa4, 0xfe, 0x59, 0xe5, 0x31, 0x4e,
	0x1b, 0x89, 0x93, 0xe7, 0xbd, 0x79, 0xf3, 0x66, 0xbc, 0x0f, 0x46, 0xe6, 0x54, 0x4b, 0x7d, 0x5b,
	0xab, 0xca, 0x54, 0xd8, 0xa7, 0xcf, 0xfc, 0x2b, 0x0c, 0x79, 0xf5, 0xf0, 0xac, 0x4d, 0x54, 0xe0,
	0x04, 0x7a, 0x65, 0xe1, 0x5b, 0x81, 0x15, 0x7a, 0xbc, 0x57, 0x16, 0x38, 0x83, 0xbe, 0x92, 0xf5,
	0xd3, 0xc9, 0xef, 0x11, 0xd5, 0x82, 0xf9, 0x1f, 0x1b, 0xc6, 0xed, 0xc8, 0x4e, 0x6a, 0x9d, 0xef,
	0x25, 0xde, 0xbc, 0xce, 0x8d, 0x16, 0xd3, 0xd6, 0xfe, 0xb6, 0x33, 0x25, 0xa3, 0xcf, 0x30, 0xd0,
	0x52, 0xeb, 0xb2, 0x3a, 0x92, 0xd5, 0x05, 0x55, 0xd7, 0xc7, 0x3b, 0x70, 0x9a, 0x2b, 0x7d, 0x3b,
	0xb0, 0xc2, 0xc9, 0xe2, 0xe6, 0x8d, 0xee, 0xbc, 0xef, 0x8c, 0xb2, 0x53, 0x2d, 0x39, 0x89, 0x11,
	0xc1, 0x29, 0x72, 0x93, 0xfb, 0x4e, 0x60, 0x85, 0x57, 0x9c, 0x6a, 0xf4, 0x9b, 0x9d, 0xea, 0x45,
	0x2a, 0xed, 0xf7, 0x03, 0x3b, 0xbc, 0xe2, 0x1d, 0xc4, 0x8f, 0x30, 0x79, 0x7c, 0x56, 0x4a, 0x1e,
	0x8d, 0x38, 0xe4, 0xda, 0x48, 0xe5, 0xbb, 0x34, 0x37, 0x3e, 0xb3, 0x3b, 0x22, 0xf1, 0x0b, 0x5c,
	0x3f, 0x3e, 0x95, 0xa4, 0x6a, 0xf7, 0x8a, 0xb2, 0xf0, 0x07, 0x81, 0x15, 0x3a, 0x7c, 0xda, 0x36,
	0xce, 0xf7, 0x44, 0x05, 0x7e, 0x80, 0xa1, 0x92, 0x2f, 0x25, 0xfd, 0xe1, 0x90, 0x24, 0xaf, 0x78,
	0xfe, 0xdb, 0x02, 0xf8, 0x77, 0x31, 0x22, 0x4c, 0x56, 0x9c, 0x2d, 0x33, 0x26, 0x52, 0x96, 0xa6,
	0x51, 0x12, 0x7b, 0xef, 0x1a, 0xee, 0x9e, 0x6d, 0xd9, 0x7f, 0x9c, 0x85, 0xef, 0x61, 0x1a, 0xf1,
	0x95, 0x58, 0xf3, 0x64, 0x27, 0x56, 0xdb, 0x88, 0xc5, 0x99, 0xd7, 0xc3, 0x6b, 0x18, 0x37, 0x64,
	0x96, 0x74, 0x94, 0x8d, 0x43, 0x70, 0xbe, 0x47, 0xf1, 0xc6, 0x73, 0x70, 0x06, 0xde, 0x8e, 0xa5,
	0xe9, 0x72, 0xc3, 0x44, 0xb2, 0x16, 0xf7, 0x6c, 0x99, 0x7d, 0xf3, 0xfa, 0x08, 0xe0, 0xae, 0x92,
	0x78, 0x1d, 0x6d, 0x3c, 0x17, 0x07, 0x60, 0x2f, 0xe3, 0x1f, 0xde, 0x60, 0x2e, 0x60, 0x94, 0x1e,
	0xf3, 0x5a, 0xff, 0xac, 0xcc, 0xb6, 0xda, 0x37, 0x41, 0x97, 0xc7, 0x42, 0xfe, 0xa2, 0x0c, 0x5d,
	0xde, 0x82, 0xe6, 0x55, 0x8d, 0x54, 0x07, 0x8a, 0xcc, 0xe5, 0x54, 0xe3, 0x27, 0xb0, 0x0f, 0x7a,
	0x4f, 0xe9, 0x8c, 0x16, 0xb3, 0x4b, 0xe9, 0xf0, 0x46, 0xf0, 0xe0, 0x52, 0xe7, 0xee, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe1, 0xfe, 0xab, 0xd4, 0x73, 0x02, 0x00, 0x00,
}
